# prezto.toml
add_newline = false

# A minimal left prompt
format = """$directory$character"""

# move the rest of the prompt to the right
right_format = """$python$status$all"""

[character]
success_symbol = "[](red)[](yellow)[](green)"
error_symbol = "[](red)[](yellow)[](green)"
# vicmd_symbol = "[](green)[](yellow)[](red)"

[git_branch]
format = '[$branch]($style) '
style = 'bold green'

[python]
style = "#3C3836 bg:none"
format = '[(\($virtualenv\) )]($style)'
pyenv_prefix = 'pyenv'
pyenv_version_name = true

[git_status]
conflicted = ""
deleted = "󰗨"
modified = ""
stashed = ""
staged = ""
renamed = ""
untracked = ""
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
ignore_submodules = true

# [git_status]
# format = '$all_status$ahead_behind '
# ahead = '[⬆](bold purple) '
# behind = '[⬇](bold purple) '
# staged = '[✚](green) '
# deleted = '[✖](red) '
# renamed = '[➜](purple) '
# stashed = '[✭](cyan) '
# untracked = '[◼](white) '
# modified = '[✱](blue) '
# conflicted = '[═](yellow) '
# diverged = '⇕ '
# up_to_date = ''

[directory]
style = "blue"
truncation_length = 1
truncation_symbol = ""
fish_style_pwd_dir_length = 1

[cmd_duration]
format = '[$duration]($style) '

[line_break]
disabled = true

[status]
disabled = false
symbol = '✘ '

[nodejs]
symbol = ""
disabled = true
style = "bold #9900ff bg:#000000"
format = '[[ $symbol ($version) ](bg:#000000)]($style)'
